[profile.default]
src = "src"
out = "out"
libs = ["lib"]

rpc-endpoints = {sepolia-eth = "${SEPOLIA_RPC_URL}", opt-sepolia = "${OP_SEPOLIA_RPC_URL}"}
remappings = [
    "@openzeppelin=lib/openzeppelin-contracts/",
    "@ccip/contracts=lib/chainlink-ccip/chains/evm/contracts/",
    "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/",
    "@chainlink/local/=lib/chainlink-local/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
